# Generated by Django 2.0.6 on 2018-06-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivelesscar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('carid', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('battery', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'drivelesscar',
                'managed': False,
            },
        ),
    ]
